#' Create diaQTL input files from PolyOrigin output
#' 
#' Create diaQTL input files from PolyOrigin output
#' 
#' Creates the pedigree (diaQTL_pedfile.csv) and genotype (diaQTL_genofile.csv) input files needed for \code{\link{read_data}} from the polyancestry output file generated by the PolyOrigin software. PolyOrigin version 1 only outputs a genetic map in cM. To add a physical map in bp, use the option \code{mapfile}. The input file needed for \code{\link{phased_parents}} (diaQTL_parents.csv) is also created.
#'
#' @param filename Name of polyancestry file 
#' @param mapfile For PolyOrigin version 1, provide optional name of CSV file containing the physical map (marker, chrom, bp)
#' @param remove.outliers Should offspring flagged as outliers be removed (default is TRUE)
#' @param outstem prefix for output filenames
#' 
#' @return NULL
#'  
#' @export
#' @importFrom utils read.csv write.csv

convert_polyorigin <- function(filename,mapfile=NULL,remove.outliers=TRUE,outstem="") {
  
  if (!is.null(mapfile)) {
    physmap <- read.csv(mapfile,as.is=T)[,1:3]
    colnames(physmap) <- c("marker","chrom","bp")
  } else {
    physmap <- NULL
    #print("diaQTL_parents not generated because no physical mapfile.")
  }
  con <- file(filename,"r")
  temp <- readLines(con)
  ix <- grep("PolyOrigin",temp)
  
  k <- grep("offspringinfo",temp[ix])
  x <- strsplit(temp[c((ix[k]+2):(ix[k+1]-1))],split=",")
  ped <- data.frame(id=sapply(x,"[[",1),
                    pop=sapply(x,"[[",2),
                    stringsAsFactors = F)
  k.out <- match("isoutlier",strsplit(temp[ix[k]+1],split=",")[[1]])
  outliers <- as.logical(toupper(sapply(x,"[[",k.out)))
  if (remove.outliers) {
    outlier.id <- ped$id[which(outliers)]
    ped <- ped[!outliers,]
  }
  
  #k <- grep("ancestralgenotype",temp[ix])
  k <- grep("valentlist",temp[ix])
  x <- strsplit(temp[c((ix[k]+2):(ix[k+1]-1))],split=",")
  k.parent <- match("parent",strsplit(temp[ix[k]+1],split=",")[[1]])
  pops <- unique(apply(cbind(sapply(x,"[[",1),
                         sapply(x,"[[",k.parent)),1,paste,collapse="|"))
  y <- strsplit(pops,split="|",fixed=T)
  parents <- data.frame(pop=sapply(y,"[[",1),
                        parent1=sapply(y,"[[",2),
                        parent2=sapply(y,function(y){y[length(y)]}), #could be self
                        stringsAsFactors = F)
  ped <- merge(ped,parents,all.x=T)
  write.csv(ped[,2:4],file=paste(outstem,"diaQTL_pedfile.csv",sep=""),row.names=F)
  
  k <- grep("parentgeno",temp[ix])
  header <- setdiff(strsplit(temp[ix[k]+1],split=",",fixed=T)[[1]],"")
  parents <- unique(c(parents$parent1,parents$parent2))
  parents <- header[sort(match(parents,header))]
  
  x <- strsplit(temp[c((ix[k]+2):(ix[k+1]-1))],split=",")
  m <- length(x)
  map <- matrix("",nrow=m,ncol=3)
  colnames(map) <- c("marker","chrom","cM")
  for (i in 1:3) {
    map[,i] <- sapply(x,"[[",i)
  }

  first.parent <- min(match(parents,header))
  POversion <- ifelse(first.parent==4,1,2)

  if (!is.null(physmap)) {
    map <- cbind(map,
                 bp=physmap[match(map[,1],physmap[,1]),3])
  } else {
    iu <- match("physposbp",header,nomatch = 0)
    if (iu > 0) 
      map <- cbind(map,bp=sapply(x,"[[",iu))
  }
  
  np <- length(parents)
  pp <- matrix("",nrow=m,ncol=np)
  colnames(pp) <- parents
  for (i in 1:np) {
    v <- sapply(x,"[[",first.parent+i-1)
    if (POversion==1) {
      v <- gsub("1","0",v)
      v <- gsub("2","1",v)
    }
    pp[,i] <- v
  }
  write.csv(cbind(map,pp),paste(outstem,"diaQTL_parents.csv",sep=""),row.names=F)

  if (POversion==1) {
    k <- grep("genoprob",temp[ix])
  } else {
    k <- grep("unphasedgenoprob",temp[ix])
  }
  header <- strsplit(temp[ix[k]+1],split=",",fixed=T)[[1]]
  id <- intersect(header,ped$id)
  keep <- match(id,header)
  if (remove.outliers & any(outliers)) {
    keep <- setdiff(keep,match(outlier.id,header))
  } 
  n <- length(keep)
  genoprob <- matrix("",nrow=m,ncol=n+1)
  colnames(genoprob) <- c("marker",header[keep])
  for (j in 1:m) {
    i <- ix[k]+1+j
    x <- strsplit(temp[i],split=",",fixed=T)[[1]]
    if (POversion==2)
      x <- gsub("&","|",x)
    genoprob[j,] <- x[c(1,keep)]
  }
  write.csv(cbind(map,genoprob[match(map[,1],genoprob[,1]),-1]),
            paste(outstem,"diaQTL_genofile.csv",sep=""),row.names=F)
  close(con)
}
