#' Create diaQTL input files from polyancestry file
#' 
#' Create diaQTL input files from polyancestry file
#' 
#' Creates the pedigree (diaQTL_pedfile.csv) and genotype (diaQTL_genofile.csv) input files needed for \code{\link{read_data}} from the polyancestry output file generated by the PolyOrigin software.
#'
#' @param filename Name of polyancestry file 
#' @param remove.outliers Should offspring flagged as outliers be removed (default is TRUE)
#' 
#' @return NULL
#'  
#' @export
#' @importFrom utils read.csv write.csv

read_polyancestry <- function(filename,remove.outliers=TRUE) {
  con <- file(filename,"r")
  temp <- readLines(con)
  ix <- grep("PolyOrigin",temp)
  
  k <- grep("offspringinfo",temp[ix])
  x <- strsplit(temp[c((ix[k]+2):(ix[k+1]-1))],split=",")
  ped <- data.frame(id=sapply(x,function(x){x[1]}),pop=as.integer(sapply(x,function(x){x[2]})),stringsAsFactors = F)
  outliers <- as.logical(toupper(sapply(x,function(x){x[4]})))
  if (remove.outliers) {
    outlier.id <- ped$id[which(outliers)]
    ped <- ped[!outliers,]
  }
  
  k <- grep("ancestralgenotype",temp[ix])
  x <- strsplit(temp[c((ix[k]+2):(ix[k+1]-1))],split=",")
  parents <- apply(cbind(sapply(x,function(x){x[1]}),sapply(x,function(x){x[3]})),1,paste,collapse="|")
  parents <- unique(parents)
  y <- strsplit(parents,split="|",fixed=T)
  parents <- data.frame(pop=sapply(y,function(y){y[1]}),parent1=sapply(y,function(y){y[2]}),parent2=sapply(y,function(y){y[length(y)]}),stringsAsFactors = F)
  ped <- merge(ped,parents)
  write.csv(ped[,2:4],"diaQTL_pedfile.csv",row.names=F)
  
  k <- grep("genoprob",temp[ix])
  header <- temp[ix[k]+1]
  header <- sub("position","cM",header)
  header <- sub("chromosome","chrom",header)
  x <- strsplit(header,split=",",fixed=T)[[1]]
  keep <- 1:length(x)
  if (remove.outliers & any(outliers)) {
    keep <- setdiff(keep,match(outlier.id,x))
  } 
  out <- file("diaQTL_genofile.csv",open="w")
  writeLines(text=paste(x[keep],collapse=","),con=out)
  for (i in (ix[k]+2):length(temp)) {
    x <- strsplit(temp[i],split=",",fixed=T)[[1]]
    writeLines(text=paste(x[keep],collapse=","),con=out)
  }
  close(out)
  close(filename)
  return(NULL)
}
